apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modelService.name }}
  labels:
    app: {{ .Values.modelService.name }}
spec:
  replicas: {{ .Values.replicaCount.modelService }}
  selector:
    matchLabels:
      app: {{ .Values.modelService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.modelService.name }}
        version: {{ .Values.modelService.version | default "v1" }}
    spec:
      containers:
      - name: {{ .Values.modelService.name }}
        image: {{ .Values.image.model }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_PORT
          value: "{{ .Values.modelService.port }}"
