{{- if .Values.appV2 }}
{{- if .Values.appV2.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-v2
  labels:
    app: {{ .Values.app.name }}
    version: v2
spec:
  replicas: {{ .Values.appV2.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: v2
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.appV2.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: SHOW_ACCURACY
              value: "true"
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
            - secretRef:
                name: {{ .Values.app.name }}-secrets
          {{- if .Values.storage.enabled }}
          volumeMounts:
              - name: shared-volume
                mountPath: {{ .Values.storage.mountPath }}
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: shared-volume
          hostPath:
            path: {{ .Values.storage.path }}
            type: DirectoryOrCreate
      {{- end }}
{{- end }}
{{- end }}
