apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modelService.name }}-v1
  labels:
    app: {{ .Values.modelService.name }}
    version: v1
spec:
  replicas: {{ .Values.replicaCount.modelService }}
  selector:
    matchLabels:
      app: {{ .Values.modelService.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.modelService.name }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.modelService.name }}
        image: {{ .Values.image.model }}
        ports:
        - containerPort: {{ .Values.modelService.port }}
        env:
        - name: MODEL_SERVICE_PORT
          value: "{{ .Values.modelService.port }}"
