{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.modelService.name }}-destinationrule
  labels:
    app: {{ .Values.modelService.name }}
spec:
  host: {{ .Values.modelService.name }}
  subsets:
  - name: v1
    labels:
      app: {{ .Values.modelService.name }}
      version: v1
  - name: v2
    labels:
      app: {{ .Values.modelService.name }}
      version: v2
{{- end }}
