{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    istio: {{ .Values.istio.gatewayName }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.ingress.host }}
    {{- if .Values.ingress.prereleaseHost }}
    - {{ .Values.ingress.prereleaseHost }}
    {{- end }}
{{- end }}
