apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  smtpPassword: {{ .Values.secrets.smtpPassword | b64enc | quote }}
