apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.app.port }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    app: app
    release: test-a3
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
    - port: http
      path: /sms/metrics
      interval: 5s