apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelService.name }}
  labels:
    app: {{ .Values.modelService.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.modelService.name }}
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}