apiVersion: v2
name: team18-a3
description: Helm chart voor A3 - Operate and Monitor Kubernetes
type: application
version: 0.1.0
appVersion: "02.0"
maintainers:
  - name: Yasar Kocdas

dependencies:
  - name: kube-prometheus-stack
    version: 75.0.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: grafana
    version: 8.5.12
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled