apiVersion: v2
name: team18-final
description: Helm chart for A3 - Operate and Monitor Kubernetes
type: application
version: 0.1.0
appVersion: "0.2.0"
maintainers:
  - name: Yasar Kocdas

dependencies:
  - name: kube-prometheus-stack
    version: 75.0.0
    repository: https://prometheus-community.github.io/helm-charts
